
# {"Form data":{"shipping[address_id]":"346509",
#     "shipping[firstname]":"Roberto",
#     "shipping[lastname]":"Cartzini",
#     "shipping[email]":"carzini.r@gmail.com",
#     "shipping[tel_country_prefix]":"2618",
#     "shipping[telephone]":"12345611111",
#     "shipping[street][]":"mam mia mamamaam",
#     "shipping[street_at]":"Aziendo",
#     "shipping[postcode]":"1231111",
#     "shipping[country_id]":"IT",
#     "shipping[region_id]":"485",
#     "shipping[region]":"",
#     "shipping[city]":"Pisa",
#     "shipping[save_in_address_book]":"1",
#     "shipping[use_for_billing]":"1",
#     "billing[address_id]":"346509",
#     "billing[firstname]":"Roberto",
#     "billing[lastname]":"Cartzini",
#     "billing[email]":"carzini.r@gmail.com",
#     "billing[tel_country_prefix]":"2618",
#     "billing[telephone]":"12345611111",
#     "billing[street][]":"mam mia mamamaam",
#     "billing[postcode]":"1231111",
#     "billing[country_id]":"IT",
#     "billing[region_id]":"485",
#     "billing[region]":"",
#     "billing[city]":"Pisa",
#     "billing[save_in_address_book]":"1",
#     "billing[same_as_shipping]":"1",
#     "bitbull_invoiceinfo[bitbull_vat_number]":"",
#     "bitbull_invoiceinfo[bitbull_fiscal_code]":"","bitbull_invoiceinfo[company]":"",
#     "bitbull_invoiceinfo[bitbull_unique_code]":"","bitbull_invoiceinfo[bitbull_pec]":"","shipping_method":"tablerate_bestway",
#     "cio_shipping_method_error":"1","form_key":"8tsYb6p7QcMAN0f6",
#     "aw_giftwrap[wrap_type_id]":"2","coupon":"","payment[method]":"phoenix_cashondelivery"}}

checkout_form = {
    'name': 'Barbara',
    'surname': 'De Luca',
    'email': 'BarbaraDeLuca@teleworm.us',
    'telephone': '03741208673',
    'address': '17014-San Giuseppe Di Cairo SV',
    'city': 'Agrigento',
    'zipcode': '46030',
    'state': 'Agrigento',
    'region_id': 485,
    'birth_date': '01/02/1990',
    'gender': 123,    # 123: male, 124: female
    'product_size': 658
}